name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        php-version: ['8.1', '8.2', '8.3']
        
    name: PHP ${{ matrix.php-version }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: json
        coverage: xdebug
        
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-${{ matrix.php-version }}-
          
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Run PHPStan
      run: composer run phpstan
      
    - name: Run PHPCS
      run: composer run phpcs
      
    - name: Run unit tests
      run: vendor/bin/phpunit --testsuite=Unit --coverage-clover=coverage.xml
      
    - name: Run integration tests
      env:
        LINKBAR_API_KEY: ${{ secrets.LINKBAR_API_KEY }}
      run: |
        if [ -n "$LINKBAR_API_KEY" ]; then
          vendor/bin/phpunit --testsuite=Integration
        else
          echo "Skipping integration tests - no API key provided"
        fi
      
    - name: Upload coverage reports to Codecov
      if: matrix.php-version == '8.2'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true